apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SMTP_USER: autistamajestoso@gmail.com
  DB_HOST: auth_db
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: auth_service
  JWT_SECRET: algosecreto
  REFRESH_TOKEN_SECRET: refreshsecret
  FRONTEND_URL: http://localhost:3000
